/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-28 09:59:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717555033247L));
    _jspx_dependants.put("jar:file:/C:/Users/ggg/Desktop/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/recycle/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Quiz</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<section class=\"wrapper style1\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Content -->\r\n");
      out.write("					<article>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz01]<br>칫솔은 플라스틱 재활용 쓰레기이다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/toothbrush_img.png\"\r\n");
      out.write("								width=\"300px\" height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span> <label><input\r\n");
      out.write("								type=\"radio\" name=\"question1\" class=\"answer\"\r\n");
      out.write("								data-correct=\"false\">O</label>\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question1\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> X</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("							<br>\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">\r\n");
      out.write("								해설 : 칫솔은 플라스틱류가 아닌 일반 쓰레기로 분류해야 한다. <br> <strong\r\n");
      out.write("									style=\"color: #A9A9A9\">70% 이상이 플라스틱으로 이루어진 칫솔은 최근\r\n");
      out.write("									서울특별시 강동구에서 폐 칫솔을 모아 줄넘기, 플라스틱 화분 등으로 재활용하기 위해 <b\r\n");
      out.write("									style=\"color: #000080\"><br>'블루우체통'</b>을 만들어 친환경 프로젝트 캠페인을\r\n");
      out.write("									진행하고 있다.\r\n");
      out.write("								</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz02]<br>패스트푸드 음료컵의 뚜껑은 플라스틱에 포함된다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/뚜껑.jfif\" width=\"300px\"\r\n");
      out.write("								height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question2\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> O</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("\r\n");
      out.write("							<label><input type=\"radio\" name=\"question2\"\r\n");
      out.write("								class=\"answer\" data-correct=\"false\"> X</label>\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">해설 : 음료컵의 뚜껑은\r\n");
      out.write("								플라스틱으로 배출해야 한다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz03]<br>고추장, 간장, 쌈장 등 장류는 음식물 쓰레기이다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/장독대.jpg\" width=\"300px\"\r\n");
      out.write("								height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span> <label><input\r\n");
      out.write("								type=\"radio\" name=\"question3\" class=\"answer\"\r\n");
      out.write("								data-correct=\"false\"> O</label>\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question3\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> X</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">해설 : 고추장, 간장,\r\n");
      out.write("								쌈장 등의 장류는 염분이 높아 가축의 사료로 사용하기 어려워 일반 쓰레기로 배출해야 한다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz04]<br>깨진 유리병도 재활용이 가능하다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/깨진유리병.jpg\" width=\"300px\"\r\n");
      out.write("								height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span> <label><input\r\n");
      out.write("								type=\"radio\" name=\"question4\" class=\"answer\"\r\n");
      out.write("								data-correct=\"false\"> O</label>\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question4\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> X</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">\r\n");
      out.write("								해설 : 깨진 유리는 신문지 등으로 충분히 감싼 후, 반드시 종량제 봉투에 배출해야 한다. <br> <strong\r\n");
      out.write("									style=\"color: #A9A9A9\">단, 유리병이 아닌 일반 유리는 깨지지 않더라도 재활용이\r\n");
      out.write("									되지 않기에 꼭 일반 쓰레기로 배출해야 한다.</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz05]<br>프링글스 통은 일반 쓰레기로 배출해야 한다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/프링글스-통.jpg\" width=\"300px\"\r\n");
      out.write("								height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question5\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> O</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("							<label><input type=\"radio\" name=\"question5\"\r\n");
      out.write("								class=\"answer\" data-correct=\"false\"> X</label>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">해설 : 프링글스 통은\r\n");
      out.write("								부위별로 다른 재질로 구성되어 있어서 납작하게 눌러 부피를 최대한 줄인 다음 일반 쓰레기로 배출하는 것이 낫다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz06]<br>(무색 스티로폼과 같이) 유색 스티로폼은 분리 배출이 가능하다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/styrofoam_img.png\"\r\n");
      out.write("								width=\"300px\" height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span> <label><input\r\n");
      out.write("								type=\"radio\" name=\"question6\" class=\"answer\"\r\n");
      out.write("								data-correct=\"false\"> O</label>\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question6\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> X</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">\r\n");
      out.write("								해설 : 스티로폼은 전체가 흰 색인 것만 분리 배출이 가능하다. <br> <strong\r\n");
      out.write("									style=\"color: #A9A9A9\">유색 플라스틱이나 이물질이 묻어 있는 스티로폼, 무늬가\r\n");
      out.write("									있거나 코팅된 스티로폼은 재활용이 어렵다.</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz07]<br>코팅된 전단지도 종이와 함께 재활용이 가능하다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/smhrd_img.jpg\"\r\n");
      out.write("								width=\"300px\" height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span> <label><input\r\n");
      out.write("								type=\"radio\" name=\"question7\" class=\"answer\"\r\n");
      out.write("								data-correct=\"false\"> O</label>\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question7\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> X</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">해설 : 전단지는 표면이\r\n");
      out.write("								코팅되어 있어 재활용이 불가하므로 일반 쓰레기로 배출해야 한다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz08]<br>포장용 뽁뽁이는 비닐로 분리 배출이 가능하다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/bbogbbog_img.png\"\r\n");
      out.write("								width=\"300px\" height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question8\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> O</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("							<label><input type=\"radio\" name=\"question8\"\r\n");
      out.write("								class=\"answer\" data-correct=\"false\"> X</label>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">\r\n");
      out.write("								해설 : 깨끗한 비닐류는 분리 배출 표시가 없다고 해도 재활용이 가능하다. <br> <strong\r\n");
      out.write("									style=\"color: #A9A9A9\">일회용 봉투, 에어캡, 세탁소 비닐 같은 경우에도 비닐로\r\n");
      out.write("									재활용이 가능하지만 식품포장용 '랩'은 종량제 봉투에 버려 일반 쓰레기로 배출해야 한다. </strong>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz09]<br>거울과 유리병과 접시는 분리 배출이 가능하다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/mirror_img.png\"\r\n");
      out.write("								width=\"300px\" height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span> <label><input\r\n");
      out.write("								type=\"radio\" name=\"question9\" class=\"answer\"\r\n");
      out.write("								data-correct=\"false\"> O</label>\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question9\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> X</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">해설 : 거울은 불에 타지\r\n");
      out.write("								않는 쓰레기이기에 크기에 따라 불연성 쓰레기 봉투(마대)에 넣어서 버려야 한다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br>\r\n");
      out.write("						<div class=\"quiz\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								[Quiz10]<br>페트병의 마개는 꼭 닫아서 분리 배출해야 한다.\r\n");
      out.write("							</h3>\r\n");
      out.write("							<span><img src=\"resources/images/pet_img.png\"\r\n");
      out.write("								width=\"300px\" height=\"300px\">&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\r\n");
      out.write("							<c> <label><input type=\"radio\" name=\"question8\"\r\n");
      out.write("								class=\"answer\" data-correct=\"true\"> O</label> <span class=\"ans\"\r\n");
      out.write("								style=\"display: none;\">&nbsp&nbsp&nbsp&nbsp<strong\r\n");
      out.write("								style=\"margin-left: -60px;\">정답</strong></span> </c>\r\n");
      out.write("							<label><input type=\"radio\" name=\"question8\"\r\n");
      out.write("								class=\"answer\" data-correct=\"false\"> X</label>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"explanation\" style=\"display: none;\">\r\n");
      out.write("								해설 : 페트병의 라벨을 제거하고 내용물을 씻어 압축시킨 후에 다시 마개를 닫아 배출해야 한다. <br>\r\n");
      out.write("								<strong style=\"color: #A9A9A9\">마개는 크기가 작아 따로 떨어질 경우\r\n");
      out.write("									발견되지 못한 채 환경을 파괴할 수도 있어, 본체와 따로 분리되지 않도록 하는 것이 중요하다.</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br> <br> <br> <br> <br> <br>\r\n");
      out.write("						<button id=\"checkAnswers\" onclick=\"check()\">정답확인</button>\r\n");
      out.write("\r\n");
      out.write("					</article>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 정답확인기능 -->\r\n");
      out.write("			<script type=\"text/javascript\">\r\n");
      out.write("               function check()\r\n");
      out.write("               {\r\n");
      out.write("\r\n");
      out.write("                  const labels = document.querySelectorAll('label');\r\n");
      out.write("                  const explanations = document.querySelectorAll('.explanation');\r\n");
      out.write("                  const ans = document.querySelectorAll('.ans');\r\n");
      out.write("                  \r\n");
      out.write("                   labels.forEach(label => {\r\n");
      out.write("                       const radio = label.querySelector('input');\r\n");
      out.write("                       if (radio.dataset.correct === \"true\") {\r\n");
      out.write("                           label.classList.add('correct', 'correct-border');\r\n");
      out.write("                       } else if (radio.dataset.correct === \"false\") {\r\n");
      out.write("                           label.classList.add('incorrect', 'incorrect-border');\r\n");
      out.write("                       }\r\n");
      out.write("                   });\r\n");
      out.write("\r\n");
      out.write("                  explanations.forEach(explanation => {\r\n");
      out.write("                       explanation.style.display = 'block';\r\n");
      out.write("                  });  \r\n");
      out.write("                  \r\n");
      out.write("                  ans.forEach(ans => {\r\n");
      out.write("                     ans.style.display = 'inline';\r\n");
      out.write("                 }); \r\n");
      out.write("                  \r\n");
      out.write("                  $('c').addClass('newClass')\r\n");
      out.write("               }\r\n");
      out.write("            </script>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- UpDownBtn-->\r\n");
      out.write("		<div class=\"upBtns\">\r\n");
      out.write("			<div class=\"moveTopBtn\">↑</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"downBtns\">\r\n");
      out.write("			<div class=\"moveBottomBtn\">↓</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("				const topBtn = document.querySelector(\".moveTopBtn\");\r\n");
      out.write("				\r\n");
      out.write("				// 버튼 클릭 시 맨 위로 이동\r\n");
      out.write("				 topBtn.onclick = () => {\r\n");
      out.write("				\r\n");
      out.write("				  window.scrollTo({ top: 0, behavior: \"smooth\" });  \r\n");
      out.write("				}\r\n");
      out.write("	\r\n");
      out.write("				const bottomBtn = document.querySelector(\".moveBottomBtn\");\r\n");
      out.write("	\r\n");
      out.write("				// 버튼 클릭 시 페이지 하단으로 이동\r\n");
      out.write("				 bottomBtn.onclick = () => {\r\n");
      out.write("					 \r\n");
      out.write("				  window.scrollTo({ top: document.body.scrollHeight, behavior: \"smooth\" });\r\n");
      out.write("				};\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Scripts -->\r\n");
      out.write("	<script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/browser.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/breakpoints.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/util.js\"></script>\r\n");
      out.write("	<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
